name: C/C++ Linter

on:
  push:
    branches: [main, master, develop, multi-path]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: 'src'

      - name: Debug file structure
        run: |
          cd src
          echo "Files in workspace:"
          ls -laR
          echo "Template files:"
          find . -name "template.h"

      - name: Install clang-format
        run: sudo apt-get install -y clang-format-17

      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          tidy: false
          repository: ${{ github.repository }}
          source: 'src'  
          files: |
            **/template.h
            include/*.h
            src/**/*.h
          extensions: h,hh,hpp,hxx  
          ignore: build/ third_party/
          clang-format-version: 17
          verbose: true

      - name: Display Linter Results
        run: |
          echo "Checked files: ${{ steps.linter.outputs.checked-files }}"
          echo "Errors: ${{ steps.linter.outputs.checks-failed }}"
          cat ${{ github.workspace }}/cpp-linter.log 2>/dev/null || echo "No issues"